services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sentinelops-network
  glpi:
    image: glpi/glpi
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:80"
    networks:
      - sentinelops-network
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: unless-stopped
    environment:
      GLPI_URL: ${GLPI_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      SQLITE_DB_PATH: ${SQLITE_DB_PATH}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - sentinelops-network
   
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - sentinelops-network
volumes:
  postgres_data:

networks:
  sentinelops-network:  